name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.16.0
  firebase_auth: 3.3.17
  cloud_firestore: 3.1.14
  firebase_storage: 10.2.15
  image_picker: 0.8.5+3
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

