name: presensi
version: 4.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6
  convex_bottom_bar: ^3.1.0+1
  intl: ^0.18.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  syncfusion_flutter_datepicker: ^20.4.42
  flutter_launcher_icons: ^0.11.0
  google_fonts: ^3.0.1
  crypto: 3.0.2
  trust_location: 2.0.13
  permission_handler: ^10.2.0
  safe_device: ^1.1.2
  cached_network_image: ^3.2.3
  image_network: 2.5.1
  flutter_svg: ^1.1.6
  cool_alert: 1.1.0
  timezone: ^0.9.1
  flutter_native_timezone: 2.0.0
  new_version: 0.3.1
  flutter_native_splash: ^2.2.16
  rxdart: ^0.27.7
  syncfusion_localizations: 20.4.48
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/Sadasbor-Logo.png
  android: true
  ios: true
  web: false

flutter: 
  assets: 
    - assets/
  uses-material-design: true

