name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.16.0
  firebase_auth: 3.3.17
  cloud_firestore: 3.1.14
  firebase_storage: 10.2.15
  image_picker: 0.8.5+3
  convex_bottom_bar: 3.0.0
  intl: 0.17.0
  geolocator: 8.2.1
  geocoding: 2.0.4
  syncfusion_flutter_datepicker: 20.1.55
  flutter_launcher_icons: 0.10.0
  google_fonts: ^3.0.1
  crypto: 3.0.2
  trust_location: 2.0.13
  permission_handler: 9.2.0
  safe_device: 1.1.1
  cached_network_image: 3.2.0
  image_network: 2.5.1
  flutter_svg: 1.0.3
  cool_alert: 1.1.0
  timezone: 0.9.0
  flutter_native_timezone: 2.0.0
  new_version: 0.3.1
  flutter_native_splash: 1.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: 0.10.0

flutter_native_splash: 
  color: '#FFFFFF'
  image: assets/Sadasbor-Logo.png
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Sadasbor-Icon.png"

flutter: 
  assets: 
    - assets/
  uses-material-design: true

